
build:source:
  stage: build
  script:
    - /usr/bin/ci-config
    - /usr/bin/ci-build source
  image: registry.gitlab.com/debian-pm/tools/build:latest-amd64

build:armhf:
  stage: build
  script:
    - /usr/bin/ci-config
    - /usr/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:latest-armhf
  artifacts:
    paths:
      - ../*.deb
  tags:
    - armhf

build:arm64:
  stage: build
  script:
    - /usr/bin/ci-config
    - /usr/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:latest-arm64
  tags:
    - arm64
  artifacts:
    paths:
      - ../*.deb
